.PHONY: check-constraints clean clean_tox compile-requirements coverage diff_cover docs help pii_check \
        quality requirements selfcheck test test-all upgrade validate

.DEFAULT_GOAL := help

# For opening files in a browser. Use like: $(BROWSER)relative/path/to/file.html
BROWSER := python -m webbrowser file://$(CURDIR)/

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -not -path './.venv/*' -exec rm -rf {} +
	find . -name '*.pyc' -not -path './.venv/*' -exec rm -f {} +
	find . -name '*.pyo' -not -path './.venv/*' -exec rm -f {} +
	find . -name '*~' -not -path './.venv/*' -exec rm -f {} +
	rm -f .coverage coverage.xml
	rm -fr htmlcov/
	rm -fr build/
	rm -fr dist/
	rm -fr src/*.egg-info

clean_tox: ## clear tox requirements cache
	rm -fr .tox

coverage: clean ## generate and view HTML coverage report
	uv run pytest --cov-report html
	$(BROWSER)htmlcov/index.html

docs: ## generate Sphinx HTML documentation, including API docs
	uv run tox -e docs
	$(BROWSER)docs/_build/html/index.html

compile-requirements: ## update uv.lock for pyproject.toml changes without upgrading packages
	uv lock

upgrade: ## upgrade all packages in uv.lock and sync constraints from edx-lint
	uv run --with 'edx-lint>=6.2' edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

# Regenerates the constraints into a scratch copy and diffs, rather than
# checking `git diff`, so that it reports only this drift and not whatever else
# happens to be uncommitted in the working tree.
check-constraints: ## fail if [tool.uv].constraint-dependencies is out of date
	@cp pyproject.toml pyproject.toml.orig
	@uv run --with 'edx-lint>=6.2' edx_lint write_uv_constraints pyproject.toml >/dev/null
	@if cmp -s pyproject.toml.orig pyproject.toml; then \
	  rm -f pyproject.toml.orig; \
	else \
	  diff -u pyproject.toml.orig pyproject.toml || true; \
	  mv pyproject.toml.orig pyproject.toml; \
	  echo ""; \
	  echo "[tool.uv].constraint-dependencies is out of date with edx-lint."; \
	  echo "Run 'make upgrade' and commit the result."; \
	  exit 1; \
	fi

quality: ## check coding style with pycodestyle and pylint
	uv run tox -e quality

pii_check: ## check for PII annotations on all Django models
	uv run tox -e pii_check

requirements: clean_tox ## install development environment requirements
	uv sync --group dev

test: clean ## run tests in the current virtualenv
	uv run pytest

diff_cover: test ## find diff lines that need test coverage
	uv run diff-cover coverage.xml

test-all: ## run tests on every supported Python/Django combination, plus quality and docs
	uv run tox

validate: quality pii_check test ## run tests and quality checks

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."
